name: Build and Release TreaYT

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Display dotnet version
      run: dotnet --info

    - name: Restore dependencies
      run: dotnet restore TreaYT.csproj

    - name: Build application
      run: dotnet build TreaYT.csproj --configuration Release --no-restore

    - name: Publish application
      run: dotnet publish TreaYT.csproj --configuration Release --runtime win-x64 --self-contained true --output ./publish --no-build

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: TreaYT-Build
        path: ./publish